// Sample Tasks Data (in a real app, this would come from an API)
export const sampleTasks = [
  {
    id: 1,
    name: "Redesign homepage",
    description: "Create a new design for the homepage",
    status: "in-progress",
    priority: "high",
    dueDate: "2025-05-15",
    assignee: { id: 1, name: "John Doe" },
    tags: ["Design", "UI/UX"],
  },
  {
    id: 2,
    name: "Fix payment bug",
    description: "Investigate and fix payment processing issue",
    status: "todo",
    priority: "high",
    assignee: { id: 3, name: "Mike Johnson" },
    tags: ["Bug", "Critical"],
  },
  {
    id: 3,
    name: "Write documentation",
    description: "Create user documentation for new features",
    status: "review",
    priority: "medium",
    dueDate: "2025-04-30",
    assignee: { id: 2, name: "Jane Smith" },
    tags: ["Documentation"],
  },
  {
    id: 4,
    name: "Implement authentication",
    description: "Add user authentication system",
    status: "todo",
    priority: "high",
    tags: ["Backend", "Security"],
  },
  {
    id: 5,
    name: "Optimize database",
    description: "Improve database query performance",
    status: "in-progress",
    priority: "medium",
    dueDate: "2025-05-05",
    assignee: { id: 3, name: "Mike Johnson" },
    tags: ["Performance", "Database"],
  }
] 