// Mock task data for the calendar
export const mockTasks = [
  {
    id: 1,
    title: "Redesign homepage",
    description: "<p>Create a new design for the homepage with improved user experience and modern aesthetics.</p>",
    status: "in-progress",
    priority: "high",
    assignee: {
      id: 1,
      name: "John Doe",
      avatar: "/mystical-forest-spirit.png",
    },
    dueDate: "2025-05-15",
    tags: ["Design", "UI/UX"],
  },
  {
    id: 2,
    title: "Implement authentication system",
    description: "<p>Set up user authentication with login, registration, and password reset functionality.</p>",
    status: "todo",
    priority: "high",
    assignee: {
      id: 3,
      name: "Mike Johnson",
      avatar: "/mystical-forest-spirit.png",
    },
    dueDate: "2025-05-10",
    tags: ["Backend", "Security"],
  },
  {
    id: 3,
    title: "Create API documentation",
    description: "<p>Document all API endpoints with examples and response schemas.</p>",
    status: "review",
    priority: "medium",
    assignee: {
      id: 2,
      name: "Jane Smith",
      avatar: "/mystical-forest-spirit.png",
    },
    dueDate: "2025-04-30",
    tags: ["Documentation", "API"],
  },
  {
    id: 4,
    title: "Fix payment processing bug",
    description: "<p>Investigate and fix the issue with payment processing on the checkout page.</p>",
    status: "done",
    priority: "high",
    assignee: {
      id: 1,
      name: "John Doe",
      avatar: "/mystical-forest-spirit.png",
    },
    dueDate: "2025-04-20",
    tags: ["Bug", "Critical"],
  },
  {
    id: 5,
    title: "Optimize database queries",
    description: "<p>Improve performance by optimizing slow database queries.</p>",
    status: "in-progress",
    priority: "medium",
    assignee: {
      id: 3,
      name: "Mike Johnson",
      avatar: "/mystical-forest-spirit.png",
    },
    dueDate: "2025-05-05",
    tags: ["Performance", "Database"],
  },
  {
    id: 6,
    title: "Quarterly team review",
    description: "<p>Conduct quarterly performance review with the development team.</p>",
    status: "todo",
    priority: "medium",
    assignee: {
      id: 1,
      name: "John Doe",
      avatar: "/mystical-forest-spirit.png",
    },
    dueDate: "2025-05-20",
    tags: ["Meeting", "Management"],
  },
  {
    id: 7,
    title: "Update privacy policy",
    description: "<p>Review and update the privacy policy to comply with new regulations.</p>",
    status: "todo",
    priority: "high",
    assignee: {
      id: 2,
      name: "Jane Smith",
      avatar: "/mystical-forest-spirit.png",
    },
    dueDate: "2025-04-25",
    tags: ["Legal", "Compliance"],
  },
  {
    id: 8,
    title: "Implement dark mode",
    description: "<p>Add dark mode support to the application.</p>",
    status: "in-progress",
    priority: "low",
    assignee: {
      id: 3,
      name: "Mike Johnson",
      avatar: "/mystical-forest-spirit.png",
    },
    dueDate: "2025-05-12",
    tags: ["UI/UX", "Feature"],
  },
  {
    id: 9,
    title: "Client presentation",
    description: "<p>Prepare and deliver presentation to the client about project progress.</p>",
    status: "todo",
    priority: "high",
    assignee: {
      id: 1,
      name: "John Doe",
      avatar: "/mystical-forest-spirit.png",
    },
    dueDate: "2025-04-28",
    tags: ["Meeting", "Client"],
  },
  {
    id: 10,
    title: "Refactor authentication module",
    description: "<p>Improve code quality and performance of the authentication module.</p>",
    status: "review",
    priority: "medium",
    assignee: {
      id: 3,
      name: "Mike Johnson",
      avatar: "/mystical-forest-spirit.png",
    },
    dueDate: "2025-05-08",
    tags: ["Refactoring", "Security"],
  },
]
